language: node_js
node_js:
  - '4'
  - '5'
  - stable

addons:
  firefox: 'latest'

before_script:
  - npm install -g npm
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm run test
